### ISSUE TITLE
folder_HRのソースコードがコンパイルできません。

### ISSUE THREAD

**Issue by tannakaken** [tannakaken/nugitlecture2020#10]
@RyusukeHosoya さま
あなたのプルリクエストをマージしたところ、いくつかの問題で、コンパイルが通らなくなりました。
- フォルダ名が間違ってます。
- ファイルに.texを最後につけてください。
- それを直しても、次のエラーが出ました。直し方がわかるでしょうか？
`! Misplaced alignment tab character &.
l.17     y &
            = \frac{1}{3}\times36m^{2}+\frac{1}{2}\times6m
? ^D
! Emergency stop.
l.17     y &
            = \frac{1}{3}\times36m^{2}+\frac{1}{2}\times6m`

とりあえずマージを取り消します。
直し方がわかったら、またプルリクエストを作成してください。

**Comment by RyusukeHosoya** [comment]
田中　様

ご連絡ありがとうございます。承知しました。
直してもう一度プルリクエストを作成してみます。

細谷竜介
